Repository Monkestation/MonkeStation, pull requests merged in 2022-06, with the labels that each got.

#401 Various pipe, wire, door Fixes for Meta, Box, Delta, Kilo, Pubby, Donut.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/DonutStation/DonutStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/mining_kilo.dmm
Labels: mapping

#426 Holestation Patch 3
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping

#429 Holestation Patch 4: Bruh
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping

#389 Various improvements to multi-Z travel [PORT]
  _maps/map_files/HoleStation/holestation.dmm
  _maps/map_files/debug/multiz.dmm
  code/game/atoms_movable.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/cable.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  code/modules/vehicles/ridden.dm
  icons/obj/power_cond/cables.dmi
Labels: sprites, mapping, testmerged

#428 Alt Movement "Fix"
  beestation.dme
  code/__DEFINES/keybinding.dm
  monkestation/code/datums/keybinding/passthrough.dm
Labels: testmerged

#431 [Speedmerge] Fixes Large Mining Shuttle
  _maps/shuttles/mining_box.dmm
  _maps/shuttles/mining_delta.dmm
  _maps/shuttles/mining_fland.dmm
  _maps/shuttles/mining_large.dmm
  _maps/templates/shelter_2.dmm
  _maps/templates/shelter_3.dmm
Labels: mapping

#421 Hardlight Spear traitor item
  beestation.dme
  icons/obj/implants.dmi
  monkestation/code/game/objects/items/implants/implant_hard_spear.dm
  monkestation/code/game/objects/items/storage/uplink_kits.dm
  monkestation/code/modules/uplink/uplink_items.dm
  monkestation/icons/mob/inhands/polearms_lefthand.dmi
  monkestation/icons/mob/inhands/polearms_righthand.dmi
  monkestation/icons/obj/implants.dmi
  monkestation/icons/obj/items_and_weapons.dmi
Labels: sprites

#440 BeeStation Minor Bug Fixes [Bee PORT]
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/controllers/subsystem/movement/movement_types.dm
  code/datums/elements/strippable.dm
  code/datums/mutations/speech.dm
  code/game/atoms.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/communications.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/living.dm
  code/modules/photography/camera/silicon_camera.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  tgui/packages/tgui-panel/chat/constants.js
Labels: TGUI-Changes

#441 ANOTHER Holestation Merge Conflict Patch
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping

#443 Hole Update 5: The Final Detailening (And Fixes)
  _maps/map_files/HoleStation/holestation.dmm
  monkestation/_maps/shuttles/cargo_holestation.dmm
Labels: mapping

#427 Fixes Custom Vendor and some oversights on smoothing
  code/modules/vending/_vending.dm
  monkestation/code/modules/bitmask_smoothing/code/floors.dm
  monkestation/code/modules/bitmask_smoothing/code/objects.dm
  monkestation/code/modules/bitmask_smoothing/turf/floors.dmi
Labels: testmerged

#432 bread smite bread smite we love bread smite
  code/__DEFINES/admin.dm
  code/__HELPERS/icons.dm
  code/modules/admin/verbs/randomverbs.dm
  monkestation/icons/effects/effects.dmi
Labels: Administration

#454 Aiming Rework
  code/datums/components/aiming.dm
Labels: testmerged

#452 Garbage Postpone Ticks + MC Failsafe Recovery
  code/__DEFINES/MC.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/spaceman_dmm.dm
  code/__HELPERS/_lists.dm
  code/_debugger.dm
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/processing/orbits.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/timer.dm
  code/controllers/subsystem/zclear.dm
  code/datums/datum.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/tgchat/to_chat.dm
Labels: Administration, testmerged

#436 Solar Panel [TG PORT] + Refactor
  beestation.dme
  code/__DEFINES/dcs/signals/signals_global_object.dm
  code/__DEFINES/power/power.dm
  code/__HELPERS/matrices.dm
  code/controllers/subsystem/sun.dm
  code/datums/mutable_appearance.dm
  code/game/atoms.dm
  code/game/objects/objs.dm
  code/modules/power/solar.dm
  code/modules/power/solar/solar.dm
  code/modules/power/solar/solar_assembly.dm
  code/modules/power/solar/solar_control.dm
  code/modules/power/solar/tracker.dm
  code/modules/power/tracker.dm
  goon/icons/obj/power.dmi
  monkestation/icons/obj/power/solar.dmi
  tgui/packages/tgui/interfaces/SolarControl.js
Labels: TGUI-Changes, testmerged

#402 Reaction lookup and Addiction refactoring [PORT from TG]
  beestation.dme
  code/__DEFINES/actionspeed_modification.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/reagents.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/reagents.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/addictions.dm
  code/datums/components/mood.dm
  code/datums/mind.dm
  code/datums/mood_events/drug_events.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/status_effects/drugs.dm
  code/datums/traits/negative.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/actionspeed/modifiers/addiction.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  code/modules/reagents/withdrawl/_addiction.dm
  code/modules/reagents/withdrawl/generic_addiction.dm
  code/modules/surgery/organs/eyes.dm
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tgui/packages/tgui/interfaces/Reagents.js
  tgui/packages/tgui/interfaces/common/ReagentLookup.js
  tgui/packages/tgui/interfaces/common/RecipeLookup.js
Labels: TGUI-Changes, testmerged

#467 Anomaly Update
  beestation.dme
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  monkestation/code/game/objects/effects/anomalies.dm
  monkestation/code/modules/events/anomaly_clown.dm
  monkestation/code/modules/events/anomaly_fluidic.dm
  monkestation/code/modules/events/anomaly_frost.dm
  monkestation/code/modules/events/anomaly_monkey.dm
  monkestation/code/modules/events/anomaly_petsplosion.dm
  monkestation/code/modules/events/anomaly_radioactive.dm
  monkestation/code/modules/events/anomaly_storm.dm
  monkestation/sound/misc/frost_horn.ogg
Labels: testmerged

#465 Adds lethal injection syringe to research and seclathe
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/modules/research/designs/medical_designs.dm
Labels: mapping

#479 Chemical Press [TG PORT] + Deposits Items in ChemFridges now
  _maps/map_files/BoxStation/BoxStation.dmm
  beestation.dme
  code/__DEFINES/reagents.dm
  code/game/objects/items/RCD.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/assets/patches.dm
  code/modules/asset_cache/assets/pills.dm
  code/modules/plumbing/plumbers/bottle_dispenser.dm
  code/modules/plumbing/plumbers/chemical_press.dm
  code/modules/plumbing/plumbers/patch_dispenser.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  icons/UI_Icons/patches/bandaid.png
  icons/UI_Icons/patches/bandaid_both.png
  icons/UI_Icons/patches/bandaid_brute.png
  icons/UI_Icons/patches/bandaid_burn.png
  icons/effects/beam.dmi
  icons/obj/plumbing/plumbers.dmi
  tgui/packages/tgui/interfaces/ChemPress.js
Labels: sprites, mapping, TGUI-Changes, testmerged

#485 Fixes vent-in Icon Directions
  icons/obj/atmospherics/components/unary_devices.dmi
Labels: sprites

#445 Civilian bounties & HAUL Gauntlets 2: Economic Boogaloo
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/DonutStation/DonutStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/HoleStation/holestation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movement.dm
  code/__DEFINES/dcs/signals/signals_object.dm
  code/__DEFINES/economy.dm
  code/controllers/subsystem/economy.dm
  code/game/atoms_movable.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/cargo/export_scanner.dm
  code/modules/cargo/exports.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/economy/account.dm
  code/modules/events/pirates.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/datums/components/pricetag.dm
  monkestation/code/datums/components/strong_pull.dm
  monkestation/code/game/machinery/civilian_bounties.dm
  monkestation/code/game/objects/items/circuitboards/computer_circuitboards.dm
  monkestation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  monkestation/code/modules/cargo/exports/civilian_bounty.dm
  monkestation/code/modules/clothing/gloves/special.dm
  monkestation/code/modules/research/designs/comp_board_designs.dm
  monkestation/code/modules/research/designs/machine_designs.dm
  monkestation/code/modules/research/designs/misc_designs.dm
  monkestation/icons/mob/hands.dmi
  monkestation/icons/obj/clothing/gloves.dmi
  monkestation/icons/obj/economy.dmi
  monkestation/icons/obj/objects.dmi
  monkestation/sound/machines/wewewew.ogg
  tgui/packages/tgui/interfaces/CivCargoHoldTerminal.js
Labels: mapping, TGUI-Changes, testmerged

#489 Moth wings can now open (BEE PORT)
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/moth_wingsopen.dmi
Labels: sprites

#488 BeeStation Updates 6/22
  beestation.dme
  code/controllers/subsystem/processing/orbits.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/dna_scanner.dm
  code/game/machinery/ecto_sniffer.dm
  code/game/machinery/quantum_pad.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/events/plasma_decon.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/metacoin/metacoin.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/pool/pool.dm
  code/modules/power/lighting.dm
  code/modules/power/singularity/emitter.dm
  code/modules/surgery/anesthetic_machine.dm
  code/modules/vending/cartridge.dm
  config/game_options.txt
  icons/obj/pda.dmi
  tools/HubMigrator/HubMigrator.dm
  tools/UpdatePaths/clothingunderrepath.txt
  tools/WebhookProcessor/github_webhook_processor.php
  tools/minibot/minibot.py
Labels: sprites, Config Update, tools

#483 Fixes Hard Delete on cables
  code/modules/power/cable.dm
Labels: testmerged

#491 Fixes Runtime on blurry_eye proc + Harddel on plane_master_controller
  code/_onclick/hud/map_popups.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/plane_master_controller.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/devices/spyglasses.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: testmerged

#495 New Ipc Chassis: Star Industrial
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/species/ipc/bodyparts.dmi
Labels: sprites

#478 Conveyor Updates [TG PORT]
  beestation.dme
  code/datums/wires/conveyor.dm
  code/modules/recycling/conveyor.dm
  code/modules/recycling/conveyor/conveyor.dm
  code/modules/recycling/conveyor/conveyor_guide.dm
  code/modules/recycling/conveyor/conveyor_stack.dm
  monkestation/icons/obj/machinery/recycling.dmi
Labels: testmerged
