Repository Monkestation/MonkeStation, pull requests merged in 2022-08, with the labels that each got.

#606 Violent shotgun sound changes. For fun.
  sound/weapons/shotguninsert.ogg
  sound/weapons/shotgunpump.ogg
  sound/weapons/shotgunshot.ogg
Labels: sound

#612 Gives Pubbystation the new clown box
  _maps/RandomRooms/3x5/sk_rdm085_hank.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/default_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/hobo_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/japanese_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/pool_bar.dmm
Labels: mapping

#605 Jukebox Soundtrack Usage
  beestation.dme
  code/_onclick/hud/credits.dm
  code/controllers/subsystem/soundtrack.dm
  code/controllers/subsystem/ticker.dm
  code/datums/soundtrack.dm
  code/game/machinery/dance_machine.dm
  config/jukebox_music/README.txt
Labels: Config Update, testmerged

#593 Monkey + Dog AI Updates [TG Ports]
  beestation.dme
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_simple.dm
  code/__DEFINES/monkeys.dm
  code/__DEFINES/song.dm
  code/__HELPERS/ai.dm
  code/datums/ai/_ai_controller.dm
  code/datums/ai/dog/dog_behaviors.dm
  code/datums/ai/dog/dog_controller.dm
  code/datums/ai/generic/generic_behaviors.dm
  code/datums/ai/generic/generic_subtrees.dm
  code/datums/ai/idle_behaviors/_idle_behavior.dm
  code/datums/ai/idle_behaviors/idle_dog.dm
  code/datums/ai/idle_behaviors/idle_monkey.dm
  code/datums/ai/idle_behaviors/idle_random_walk.dm
  code/datums/ai/monkey/monkey_behaviors.dm
  code/datums/ai/monkey/monkey_controller.dm
  code/datums/ai/monkey/monkey_subtrees.dm
  code/datums/weakrefs.dm
  code/modules/instruments/songs/_song.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/power/lighting/light.dm
  monkestation/code/__HELPERS/unsorted.dm
  sound/creatures/dog/growl1.ogg
  sound/creatures/dog/growl2.ogg
Labels: sound, testmerged

#591 BluBox p1 - Redesigning Random Shit On BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#620 Minor Metastation Fixies
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#624 Minor text fixes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#569 Adds plane masters to camera console
  code/_onclick/hud/plane_master.dm
  code/game/machinery/computer/camera.dm
  code/game/turfs/open/openspace.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: testmerged

#513 Tile QoL changes More to come in sister pr's
  beestation.dme
  code/__DEFINES/dcs/signals/signals_painting.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/_onclick/hud/radial.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/assets.dm
  code/datums/elements/turf_transparency.dm
  code/datums/materials/_material.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items/airlock_painter.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/objects/items/stacks/tiles/tile_reskinning.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/artstuff.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/mineral_floor.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  code/game/turfs/open/glass.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/techweb/all_nodes.dm
  config/config.txt
  icons/effects/random_spawners.dmi
  icons/obj/objects.dmi
  icons/obj/tiles.dmi
  icons/turf/decals.dmi
  icons/turf/floors.dmi
  icons/turf/floors/glass.dmi
  icons/turf/floors/plasma_glass.dmi
  icons/turf/floors/reinf_glass.dmi
  icons/turf/floors/reinf_plasma_glass.dmi
  tgui/packages/tgui/interfaces/DecalPainter.js
  tgui/packages/tgui/interfaces/DecalPainter.tsx
Labels: sprites, Config Update, TGUI-Changes, testmerged

#602 Conveyor Fix + Tool Msg Adjustments
  code/modules/recycling/conveyor/conveyor.dm
Labels: testmerged

#586 More APC TG Updates [TG PORTS]
  beestation.dme
  code/__DEFINES/alerts.dm
  code/__DEFINES/power/apc_defines.dm
  code/_onclick/hud/alert.dm
  code/modules/antagonists/clock_cult/items/integration_cog.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/power/apc/apc_appearance.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_malf.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/apc/apc_tool_act.dm
  code/modules/power/terminal.dm
Labels: testmerged

#640 atmos analyzers report volume even for empty containers
  code/game/objects/items/devices/scanners.dm
Labels: Quality of Life

#635 Attack Animation
  code/game/atoms_movable.dm
Labels: testmerged

#647 Adds Missing Bee Decals
  icons/turf/decals.dmi
Labels: sprites

#393 Smooth Movement [PORT]
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
  code/__DEFINES/movement.dm
  code/controllers/subsystem/throwing.dm
  code/controllers/subsystem/time_track.dm
  code/datums/components/orbiter.dm
  code/datums/components/riding.dm
  code/game/atoms_movable.dm
  code/game/mecha/mecha.dm
  code/game/objects/buckling.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/singularity/singularity.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: testmerged

#568 Some Runtime Fixes + Bug Fixes From TG
  code/datums/armor.dm
  code/datums/components/customizable_reagent_holder.dm
  code/datums/components/shell.dm
  code/game/alternate_appearance.dm
  code/game/atoms.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/warrant.dm
  code/game/machinery/doors/door.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/jobs/access.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/login.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/vending/_vending.dm
Labels: Administration, testmerged

#646 Gas Meter Updates + QoL
  code/__DEFINES/layers.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/meter.json
  code/modules/atmospherics/machinery/other/meter.dm
  icons/obj/atmospherics/pipes/meter.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
  monkestation/code/datums/greyscale/greyscale_configs.dm
Labels: sprites

#627 Dynamic Adjustments Part 2
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/events/operative.dm
  code/modules/events/pirates.dm
  code/modules/events/space_dragon.dm
  strings/pirates.json
Labels: testmerged

#658 Fixes Conveyors + Lowers Sounds in NastyTrap Room
  _maps/RandomRooms/5x3/sk_rdm089_nastytrap.dmm
  code/modules/recycling/conveyor/conveyor.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/recycling/disposal/pipe.dm
Labels: mapping

#657 Meter Icon Tweaks
  icons/obj/atmospherics/pipes/meter.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
Labels: sprites

#651 Adds Prevention to APC Sound Spam
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_power_proc.dm
  sound/machines/apc/PowerDown_001.ogg
  sound/machines/apc/PowerSwitch_Cover.ogg
  sound/machines/apc/PowerSwitch_Off.ogg
  sound/machines/apc/PowerSwitch_Zap.ogg
  sound/machines/apc/PowerUp_001.ogg
Labels: sound

#639 Space Heater Updates +QoL
  code/game/machinery/spaceheater.dm
  tgui/packages/tgui/interfaces/SpaceHeater.js
Labels: TGUI-Changes

#632 custom soup and salads also deepfrying fix
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/datums/components/customizable_reagent_holder.dm
  code/datums/components/edibles.dm
  code/modules/food_and_drinks/food/bowl.dm
  code/modules/food_and_drinks/food/salad.dm
  code/modules/food_and_drinks/food/soup.dm
  code/modules/mining/lavaland/ash_flora.dm
  icons/obj/food/soupsalad.dmi
Labels: sprites

#599 Examine blocks
  code/__DEFINES/chat.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/mood.dm
  code/game/atoms.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/growninedible.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: TGUI-Changes

#674 Fix #527
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#669 Adds Mothroach
  beestation.dme
  code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/meat.dm
  code/modules/mob/living/simple_animal/friendly/mothroach.dm
  icons/mob/animal.dmi
  icons/mob/pets_held.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
  icons/obj/stack_objects.dmi
Labels: sprites

#675 Custom Shuttle Fixes
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  tgui/packages/tgui/interfaces/OrbitalMap.js
  tgui/packages/tgui/interfaces/ShuttleDesignator.js
Labels: TGUI-Changes
