Repository Monkestation/MonkeStation, pull requests merged in 2022-11, with the labels that each got.

#773 Changes how atmospherics looks and moves its pipes around a lot.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/DonutStation/DonutStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, testmerged

#745 Chromehead drip
  code/game/machinery/aug_manipulator.dm
  icons/mob/augmentation/augments_medical.dmi
  icons/mob/augmentation/augments_mining.dmi
Labels: sprites

#806 Stowaways now get a 2-use maintenance ID
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/access.dm
  icons/obj/card.dmi
  monkestation/code/__HELPERS/unsorted.dm
  monkestation/code/datums/traits/negative.dm
Labels: sprites

#804 Adjust AI lawsets
  code/datums/ai_laws.dm
  config/game_options.txt
  config/silicon_laws.txt
Labels: Config Update

#819 Moves Battle Royale Commands to "Fun"
  code/modules/admin/battle_royale.dm
Labels: Administration

#840 1984s some posters again
  icons/obj/contraband.dmi
Labels: sprites

#823 Changes the New Space Law event into a station trait
  beestation.dme
  monkestation/code/modules/events/new_space_law.dm
  monkestation/strings/new_space_laws.txt
Labels: testmerged

#843 Github Test Fix
  .github/workflows/continuous_integration.yml
Labels: GitHub

#844 Revert "Adds whoopee cushions and makes it easier to add new farts"
  code/game/objects/items/toys.dm
  code/modules/cargo/packs.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/games.dm
  icons/obj/toy.dmi
  monkestation/code/modules/surgery/organs/butts.dm
  strings/farts.txt
Labels: sprites
