Repository Monkestation/MonkeStation, pull requests merged in 2022-10, with the labels that each got.

#757 Curses the BoxStation horse mask.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#772 Fixes vending machines giving away free items
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: TGUI-Changes

#739 optimizes manifests, fixes some 1 letter vars, also makes consoles use real pictures [Port]
  code/__DEFINES/mobs.dm
  code/__HELPERS/icons.dm
  code/datums/datacore.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: testmerged

#783 adds a poster and fixes the liz poster
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: sprites

#766 Box Station Blues
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#789 Toxins Unfunk
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#791 Labor Camp Fixes
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Mining/Lavaland.dmm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/machinery/gulag_item_reclaimer.dm
  code/game/machinery/gulag_teleporter.dm
  code/game/objects/items/cards_ids.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/mining/machine_processing.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  tgui/packages/tgui/interfaces/GulagTeleporterConsole.js
Labels: mapping, TGUI-Changes, testmerged

#795 Adds new crayon drawings, fixes tile coloring and some grammar
  code/__HELPERS/text.dm
  code/game/objects/items/crayons.dm
  icons/effects/crayondecal.dmi
Labels: sprites

#798 Adds chemical bags to the chemmaster [port]
  beestation.dme
  code/__DEFINES/reagents.dm
  code/game/atoms.dm
  code/game/machinery/iv_drip.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
Labels: TGUI-Changes

#793 Ports painting improvements, admin painting managers, and some tgui elements
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/persistent_paintings.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/painting_manager.dm
  code/modules/art/paintings.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/silicon/ai/ai_portrait_picker.dm
  code/modules/modular_computers/file_system/programs/portrait_printer.dm
  code/modules/tgui/tgui_alert.dm
  code/modules/tgui/tgui_input_number.dm
  code/modules/tgui/tgui_input_text.dm
  code/modules/vending/games.dm
  icons/mob/inhands/equipment/palette_lefthand.dmi
  icons/mob/inhands/equipment/palette_righthand.dmi
  icons/obj/artstuff.dmi
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/interfaces/AlertModal.js
  tgui/packages/tgui/interfaces/Canvas.js
  tgui/packages/tgui/interfaces/Canvas.tsx
  tgui/packages/tgui/interfaces/NtosPortraitPrinter.js
  tgui/packages/tgui/interfaces/NumberInputModal.tsx
  tgui/packages/tgui/interfaces/PaintingAdminPanel.tsx
  tgui/packages/tgui/interfaces/PortraitPicker.js
  tgui/packages/tgui/interfaces/TextInputModal.tsx
  tgui/packages/tgui/interfaces/common/InputButtons.tsx
  tgui/packages/tgui/interfaces/common/Loader.tsx
  tgui/packages/tgui/styles/interfaces/AlertModal.scss
  tgui/packages/tgui/styles/main.scss
Labels: sprites, Administration, TGUI-Changes, testmerged

#751 Fixes various things related to Kapu Limbs
  code/__HELPERS/cmp.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/mobs.dm
  code/modules/antagonists/devil/devil.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/apid_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/ethereal_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/ipc_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/moth_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/oozeling_bodyparts.dm
  code/modules/surgery/bodyparts/species_parts/plasmaman_bodyparts.dm
  icons/mob/left_leg_mask_base.dmi
  icons/mob/mutant_bodyparts.dmi
  icons/mob/species/apid/bodyparts.dmi
  icons/mob/species/lizard/bodymarks.dmi
  icons/mob/species/lizard/bodyparts.dmi
  icons/mob/species/lizard/frills.dmi
  icons/mob/species/lizard/horns.dmi
  icons/mob/species/lizard/snouts.dmi
  icons/mob/species/lizard/spines.dmi
  icons/mob/species/lizard/tails.dmi
  monkestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
  monkestation/code/modules/surgery/bodyparts/species_parts/simian_bodyparts.dm
Labels: sprites, testmerged

#645 Chem Gases revived
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/reagents.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/fire_burning.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/obj_defense.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/hydroponics/seeds.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/lungs.dm
  icons/effects/atmospherics.dmi
  monkestation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  monkestation/code/game/objects/items/gasifier.dm
  monkestation/code/modules/liquids/code/liquid_systems/liquid_effect.dm
  monkestation/code/modules/liquids/code/liquid_systems/liquid_groups.dm
  monkestation/code/modules/liquids/code/liquid_systems/liquid_turf.dm
  monkestation/code/modules/reagents/chemistry/machinery/atmos_machine.dm
  monkestation/code/modules/research/designs/machine_designs.dm
  tgui/packages/tgui/interfaces/SmokeMachine.js
Labels: sprites, mapping, TGUI-Changes, testmerged
