Repository Monkestation/MonkeStation, pull requests merged in 2022-07, with the labels that each got.

#496 Proper Evaporation system, and better mopping [TEST-MERGE]
  code/__DEFINES/liquids.dm
  code/game/objects/items/mop.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  monkestation/code/modules/liquids/code/liquid_systems/liquid_effect.dm
  monkestation/code/modules/liquids/code/liquid_systems/liquid_groups.dm
Labels: testmerged

#505 Screentips Baby! [PORT from TG]
  beestation.dme
  code/__DEFINES/layers.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/screentips.dm
  code/__DEFINES/subsystems.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screentips.dm
  code/controllers/subsystem/mouse_entered.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/openspace.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: testmerged

#510 Various building QoL's [PORT from TG]
  code/__DEFINES/construction.dm
  code/datums/components/crafting/recipes.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/floor.dm
  code/modules/assembly/doorcontrol.dm
  code/modules/mining/aux_base_camera.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/radial.dmi
  tgui/packages/tgui/interfaces/AirlockElectronics.js
Labels: sprites, TGUI-Changes

#509 Bee Updates 7-2-2022
  code/_onclick/hud/screen_objects.dm
  code/datums/action.dm
  code/datums/elements/strippable.dm
  code/datums/mind.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_simulations.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/plushes.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/client/client_procs.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/tgui/tgui.dm
  code/modules/uplink/uplink_devices.dm
  icons/effects/96x32.dmi
Labels: sprites, Administration

#507 Adds Ant and Decomposing [PORT of TG]
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/typecache.dm
  code/datums/components/decomposition.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/turfs/open/dirtystation.dm
  code/modules/food_and_drinks/food/_food.dm
  code/modules/food_and_drinks/food/bread.dm
  code/modules/food_and_drinks/food/egg.dm
  code/modules/food_and_drinks/food/misc.dm
  code/modules/food_and_drinks/food/pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/hostile/ant.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/mob/pets.dmi
  icons/mob/screen_alert.dmi
  icons/obj/food/food.dmi
  icons/obj/objects.dmi
Labels: sprites, testmerged

#526 Bullterrier PAI Holochassis
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
  icons/mob/pai_item_head.dmi
  icons/mob/pai_item_lh.dmi
  icons/mob/pai_item_rh.dmi
  monkestation/icons/mob/pai.dmi
Labels: sprites

#539 Make ghosts continuously float
  code/modules/mob/dead/observer/observer.dm
Labels: Feature

#550 City of Cogs has a smaller void now
  _maps/map_files/generic/CityOfCogs.dmm
Labels: mapping

#516 Better Crafting Menu and Better Cargo Console
  code/__HELPERS/icons.dm
  code/datums/elements/strippable.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/clothing/clothing.dm
  icons/UI_Icons/inventory/back.png
  icons/UI_Icons/inventory/belt.png
  icons/UI_Icons/inventory/collar.png
  icons/UI_Icons/inventory/ears.png
  icons/UI_Icons/inventory/glasses.png
  icons/UI_Icons/inventory/gloves.png
  icons/UI_Icons/inventory/hand_l.png
  icons/UI_Icons/inventory/hand_r.png
  icons/UI_Icons/inventory/head.png
  icons/UI_Icons/inventory/id.png
  icons/UI_Icons/inventory/mask.png
  icons/UI_Icons/inventory/neck.png
  icons/UI_Icons/inventory/pocket.png
  icons/UI_Icons/inventory/shoes.png
  icons/UI_Icons/inventory/suit.png
  icons/UI_Icons/inventory/suit_storage.png
  icons/UI_Icons/inventory/uniform.png
  tgui/.eslintrc.yml
  tgui/packages/common/collections.spec.ts
  tgui/packages/common/collections.ts
  tgui/packages/common/fp.js
  tgui/packages/common/perf.js
  tgui/packages/common/react.ts
  tgui/packages/common/redux.js
  tgui/packages/common/types.ts
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/Box.tsx
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/interfaces/PersonalCrafting.js
  tgui/packages/tgui/interfaces/PersonalCrafting.tsx
  tgui/packages/tgui/interfaces/StripMenu.tsx
  tgui/packages/tgui/styles/interfaces/PersonalCrafting.scss
  tgui/packages/tgui/styles/main.scss
  tgui/tsconfig.json
Labels: TGUI-Changes, testmerged

#549 MORE AI SPRITES OK?
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
Labels: sprites

#564 Fix overaggressive text brightness sanitization
  code/__HELPERS/sanitize_values.dm
  code/modules/client/preferences_savefile.dm
Labels: Quality of Life

#561 Adds missing smooth icons for clockwork catwalk
  _maps/map_files/generic/CityOfCogs.dmm
  beestation.dme
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  monkestation/code/modules/bitmask_smoothing/code/floors.dm
  monkestation/code/modules/bitmask_smoothing/obj/smooth_structures/catwalk_clockwork_large.dmi
  monkestation/code/modules/bitmask_smoothing/obj/smooth_structures/lattice_clockwork.dmi
  monkestation/code/modules/bitmask_smoothing/obj/smooth_structures/lattice_clockwork_large.dmi
Labels: mapping

#560 Clown Crate + Locker
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/DonutStation/DonutStation.dmm
  _maps/map_files/HoleStation/holestation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/modules/cargo/packs.dm
  monkestation/code/game/objects/structures/crates_lockers/closets/secure/clown.dm
  monkestation/code/game/objects/structures/crates_lockers/crates/secure.dm
  monkestation/icons/obj/closet.dmi
  monkestation/icons/obj/crates.dmi
Labels: mapping

#482 Janitor QoL Additions [TG PORT] Super Deluxe Edition
  beestation.dme
  code/__DEFINES/dcs/signals/signals_janitor.dm
  code/datums/components/janitor/vacuum.dm
  code/datums/greyscale/json_configs/janicart_upgrade.json
  code/datums/greyscale/json_configs/janicart_upgrade_installed.json
  code/game/objects/items/clown_items.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
  code/modules/cargo/bounties/science.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vehicles/pimpin_ride.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/vehicle_key.dm
  icons/obj/vehicles.dmi
  monkestation/code/datums/greyscale/greyscale_configs.dm
  monkestation/icons/obj/janitor/janicart_upgrade.dmi
  monkestation/icons/obj/janitor/janitor.dmi
  monkestation/icons/obj/janitor/janitorial_cart.dmi
  monkestation/icons/obj/vehicles/janicart.dmi
Labels: sprites, testmerged

#573 Brings our MC up to date with TG [UPSTREAM]
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/_tick.dm
  code/controllers/admin.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/failsafe.dm
  code/controllers/globals.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/disease.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/metrics.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/server_maint.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/stat.dm
  code/controllers/subsystem/time_track.dm
  code/controllers/subsystem/title.dm
  code/datums/helper_datums/stack_end_detector.dm
  code/datums/weather/weather.dm
  code/game/objects/structures/traps.dm
  code/game/world.dm
  code/modules/power/lighting/light.dm
  code/modules/tgchat/to_chat.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/subsystem_metric_sanity.dm
  config/config.txt
Labels: Config Update, testmerged

#585 bump to auxmos 1.1.12 from bee
  auxtools/auxmos.dll
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  dependencies.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: tools, testmerged

#551 Makes supermatter properties auxgm-based
  code/__DEFINES/atmospherics.dm
  code/game/objects/effects/countdown.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/supermatter/supermatter.dm
Labels: testmerged

#522 A Framework for applying buffs to food [WIP] [Will need TEST-MERGE]
  beestation.dme
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/components/edibles.dm
  code/datums/traits/good.dm
  code/game/turfs/closed/minerals.dm
  code/modules/food_and_drinks/food/_food.dm
  code/modules/food_and_drinks/food/bread.dm
  code/modules/food_and_drinks/food/burger.dm
  code/modules/food_and_drinks/food/cake.dm
  code/modules/food_and_drinks/food/egg.dm
  code/modules/food_and_drinks/food/lizard.dm
  code/modules/food_and_drinks/food/meat.dm
  code/modules/food_and_drinks/food/misc.dm
  code/modules/food_and_drinks/food/pastries.dm
  code/modules/food_and_drinks/food/salad.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/emote.dm
  icons/mob/screen_alert.dmi
  monkestation/code/datums/status_effects/food_and_drinks/buffs.dm
  monkestation/code/game/objects/items/anime.dm
Labels: sprites, testmerged

#601 Reword SM/Headset Message
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration
