Repository Monkestation/MonkeStation, pull requests merged in 2022-02, with the labels that each got.

#69 Monke Strings Expansion Part 1
  monkestation/strings/random_police.txt
Labels: enhancement

#70 Monke Strings Expansion Part 2
  monkestation/strings/random_monkey_names.txt
Labels: enhancement

#66 Replace felinid species with anime trait
  _maps/map_files/CorgStation/CorgStation.dmm
  beestation.dme
  code/__DEFINES/configuration.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/traumas.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/transformation.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/machinery/race_converter.dm
  code/game/machinery/scan_gate.dm
  code/game/objects/items/devices/laserpointer.dm
  code/game/objects/items/implants/implantchair.dm
  code/game/objects/items/pet_carrier.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/pool/components/swimming_felinid.dm
  code/modules/pool/pool.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/rules.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/tails.dm
  config/game_options.txt
  monkestation/code/datums/traits/neutral.dm
  monkestation/code/game/objects/items/anime.dm
  monkestation/code/modules/mob/living/carbon/human/species_emotes.dm
  monkestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  monkestation/icons/obj/device.dmi
  strings/owo_talk.json
  strings/tips.txt
  tgui/packages/tgui/interfaces/ScannerGate.js
Labels: mapping, Administration, Config Update, TGUI-Changes

#55 Passive Discovery Research
  code/__DEFINES/research.dm
  code/controllers/subsystem/research.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/_orbital_objective.dm
Labels: enhancement

#73 Yes-Slip Shoes
  beestation.dme
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
  monkestation/code/datums/components/crafting/recipes.dm
  monkestation/code/modules/clothing/shoes/miscellaneous.dm
Labels: sprites, Feature

#80 Adds a new key config for RedBot
  code/controllers/configuration/entries/comms.dm
  config/comms.txt
  monkestation/code/controllers/subsystem/redbot.dm
Labels: Config Update

#84 adds goon default keybindings
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/client.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/keybinding.dm
  code/datums/keybinding/living.dm
  code/datums/keybinding/mob.dm
  code/modules/client/preferences.dm
  monkestation/code/datums/keybinding/human.dm
Labels: Quality of Life

#86 modularize all clothing items
  .github/CONTRIBUTING.md
  icons/mob/feet.dmi
  icons/mob/mask.dmi
  monkestation/code/modules/clothing/masks/miscellaneous.dm
  monkestation/code/modules/clothing/shoes/magboots.dm
  monkestation/code/modules/clothing/shoes/miscellaneous.dm
  monkestation/icons/mob/feet.dmi
  monkestation/icons/mob/mask.dmi
Labels: sprites, GitHub

#61 Radio Hotkey
  beestation.dme
  code/__DEFINES/keybinding.dm
  monkestation/code/datums/keybinding/living.dm
Labels: enhancement, Feature

#83 Butt Bugfixes
  monkestation/code/modules/mob/living/carbon/human/emote.dm
  monkestation/code/modules/surgery/organs/butts.dm
  monkestation/icons/obj/worn_butts.dmi
Labels: bug

#76 Markdown files and badges
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  monkestation/badges/fueled-by-potassium.svg
  tgui/README.md
  tgui/docs/component-reference.md
  tgui/docs/converting-old-tgui-interfaces.md
  tgui/docs/migration-to-v4-from-v3.md
  tgui/docs/tutorial-and-examples.md
  tgui/docs/writing-tests.md
  tools/build/README.md
  tools/hooks/README.md
  tools/mapmerge2/README.md
Labels: tools, TGUI-Changes, GitHub

#90 Duke Station Announcer
  beestation.dme
  code/datums/station_traits/neutral_traits.dm
  monkestation/code/datums/announcers/duke_announcer.dm
  monkestation/code/datums/station_traits/neutral_traits.dm
  monkestation/sound/ai/duke/Sound License.txt
  monkestation/sound/ai/duke/aimalf.ogg
  monkestation/sound/ai/duke/alerts/bonus2.ogg
  monkestation/sound/ai/duke/alerts/headsup1.ogg
  monkestation/sound/ai/duke/alerts/headsup2.ogg
  monkestation/sound/ai/duke/alerts/nerd.ogg
  monkestation/sound/ai/duke/aliens.ogg
  monkestation/sound/ai/duke/animes.ogg
  monkestation/sound/ai/duke/blob.ogg
  monkestation/sound/ai/duke/commandreport/centralcommand1.ogg
  monkestation/sound/ai/duke/commandreport/centralcommand2.ogg
  monkestation/sound/ai/duke/granomalies.ogg
  monkestation/sound/ai/duke/intercept.ogg
  monkestation/sound/ai/duke/ionstorm.ogg
  monkestation/sound/ai/duke/meteors.ogg
  monkestation/sound/ai/duke/power_off.ogg
  monkestation/sound/ai/duke/power_on.ogg
  monkestation/sound/ai/duke/radiation.ogg
  monkestation/sound/ai/duke/shuttle_arrive.ogg
  monkestation/sound/ai/duke/shuttle_call.ogg
  monkestation/sound/ai/duke/shuttle_recall.ogg
  monkestation/sound/ai/duke/spanomalies.ogg
  monkestation/sound/ai/duke/virus.ogg
  monkestation/sound/ai/duke/welcome/bonus1.ogg
  monkestation/sound/ai/duke/welcome/welcome1.ogg
  monkestation/sound/ai/duke/welcome/welcome2.ogg
  sound/roundend/apescapev1.ogg
  sound/roundend/disappointed.ogg
  sound/roundend/duke_oh_my_god.ogg
  sound/roundend/leavingtg.ogg
  sound/roundend/light_switch_roundend.ogg
  sound/roundend/roundend1.ogg
  sound/roundend/whyban.ogg
Labels: sound

#54 Florida Man Antagonist
  beestation.dme
  code/__DEFINES/cargo.dm
  icons/obj/supplypods.dmi
  monkestation/code/modules/antagonists/florida_man/florida_man.dm
  monkestation/code/modules/antagonists/florida_man/florida_man_abilities.dm
  monkestation/code/modules/antagonists/florida_man/florida_man_defines.dm
  monkestation/code/modules/antagonists/florida_man/florida_man_event.dm
  monkestation/code/modules/antagonists/florida_man/florida_man_outfits.dm
  monkestation/code/modules/cargo/supplypod.dm
  monkestation/icons/mob/actions/florida_man.dmi
  monkestation/sound/ambience/antag/floridaman.ogg
  tgui/packages/tgui/interfaces/CentcomPodLauncher.js
Labels: sprites, TGUI-Changes, Feature

#91 Cowboy Sec
  beestation.dme
  code/datums/outfit.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/jobs/job_types/security_officer.dm
  monkestation/code/datums/action.dm
  monkestation/code/modules/clothing/head/helmet.dm
  monkestation/code/modules/clothing/masks/breath.dm
  monkestation/code/modules/clothing/suits/armor.dm
  monkestation/code/modules/clothing/suits/toggles.dm
  monkestation/icons/mob/head.dmi
  monkestation/icons/mob/mask.dmi
  monkestation/icons/mob/suit.dmi
  monkestation/icons/obj/clothing/hats.dmi
  monkestation/icons/obj/clothing/masks.dmi
  monkestation/icons/obj/clothing/suits.dmi
Labels: enhancement, sprites, Feature

#58 Smooth out dizzy animation
  code/modules/mob/living/carbon/life.dm
Labels: enhancement, Quality of Life

#79 Look Forward
  config/title_music/sounds/forward.ogg
  config/title_music/sounds/lookforwardlicense.txt
Labels: Config Update, sound

#82 Chemical Flamethrowers and Reagent Explosion Fix
  code/game/objects/items/flamethrower.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  icons/mob/inhands/weapons/flamethrower_lefthand.dmi
  icons/mob/inhands/weapons/flamethrower_righthand.dmi
  icons/obj/flamethrower.dmi
Labels: enhancement, sprites, Feature

#81 Monkey Aggression Increase
  code/__DEFINES/monkeys.dm
  html/changelog.html
  html/changelogs/AutoChangeLog-pr-80.yml
Labels: enhancement, Balance

#72 Chemical Extinguishers
  code/game/objects/items/extinguisher.dm
Labels: enhancement, Balance

#63 Port of /tg/ mail system
  beestation.dme
  code/__DEFINES/economy.dm
  code/controllers/subsystem/economy.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/orderconsole.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/recycling/disposal/holder.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/shuttle/supply.dm
  code/modules/vending/wardrobes.dm
  monkestation/code/_globalvars/flavor_misc.dm
  monkestation/code/game/objects/effects/spawners/lootdrop.dm
  monkestation/code/game/objects/items/fluff_papers.dm
  monkestation/code/game/objects/items/mail.dm
  monkestation/code/modules/food_and_drinks/food/snacks_meat.dm
  monkestation/code/modules/jobs/mail_goodies/job_mail.dm
  monkestation/code/modules/reagents/reagent_containers/bottle.dm
  monkestation/icons/obj/mail.dmi
  monkestation/icons/obj/mail_crates.dmi
  monkestation/strings/junkmail.txt
Labels: Feature

#85 Changelog Addition
  monkestation/code/modules/mob/living/carbon/human/emote.dm
Labels: DO NOT MERGE

#122 Fixes incorrect atmos clothing icons
  icons/obj/clothing/suits.dmi
Labels: sprites

#129 Florida Rebalance
  monkestation/code/modules/antagonists/florida_man/florida_man.dm
  monkestation/code/modules/antagonists/florida_man/florida_man_abilities.dm
Labels: Balance

#140 Ports Honk Platinum from donkstation
  beestation.dme
  monkestation/code/modules/mob/living/simple_animal/friendly/honk_platinum.dm
  monkestation/icons/mob/pets.dmi
  monkestation/icons/mob/pets_held.dmi
  monkestation/icons/mob/pets_held_lh.dmi
  monkestation/icons/mob/pets_held_rh.dmi
Labels: sprites, Port

#144 Upstream 02/18/22
  code/__DEFINES/qdel.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/garbage.dm
  code/datums/brain_damage/phobia.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/client/client_procs.dm
  tgui/package.json
  tgui/yarn.lock
Labels: TGUI-Changes

#151 Mail Adjustments & Outfit
  beestation.dme
  code/__DEFINES/economy.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  monkestation/code/game/objects/items/mail.dm
  monkestation/code/modules/clothing/spacesuits/plasmamen.dm
  monkestation/code/modules/clothing/under/jobs/plasmaman/civilian_service.dm
  monkestation/code/modules/jobs/job_types/gimmick.dm
  monkestation/icons/mob/head.dmi
  monkestation/icons/mob/uniform.dmi
  monkestation/icons/obj/clothing/hats.dmi
  monkestation/icons/obj/clothing/uniforms.dmi
Labels: testmerged
