Repository Monkestation/MonkeStation, pull requests merged in 2022-01, with the labels that each got.

#33 Delete hot_cross_buns.ogg
  sound/roundend/hot_cross_buns.ogg
Labels: sound

#32 Stickable Objects
  beestation.dme
  code/game/objects/items/paint.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/tools/wirecutters.dm
  code/modules/jobs/job_types/clown.dm
  monkestation/code/game/objects/items/stickables.dm
  monkestation/code/modules/cargo/packs.dm
  monkestation/icons/obj/misc/stickables.dmi
Labels: Feature

#30 ports /tg/ menu with custom menu!
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/ticker.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/hud/lobby/background.dmi
  icons/hud/lobby/bottom_buttons.dmi
  icons/hud/lobby/character_setup.dmi
  icons/hud/lobby/join.dmi
  icons/hud/lobby/observe.dmi
  icons/hud/lobby/poll_overlay.dmi
  icons/hud/lobby/ready.dmi
  monkestation/code/_onclick/hud/new_player.dm
  monkestation/icons/hud/lobby/background.dmi
  monkestation/icons/hud/lobby/changelog.dmi
  monkestation/icons/hud/lobby/character_setup.dmi
  monkestation/icons/hud/lobby/join.dmi
  monkestation/icons/hud/lobby/manifest.dmi
  monkestation/icons/hud/lobby/observe.dmi
  monkestation/icons/hud/lobby/poll.dmi
  monkestation/icons/hud/lobby/ready.dmi
Labels: enhancement, sprites

#29 Test Dummy Admin Secret
  beestation.dme
  code/modules/admin/secrets.dm
  monkestation/code/game/objects/effects/misc.dm
  monkestation/code/modules/admin/verbs/testdummy.dm
  monkestation/icons/effects/96x96.dmi
  monkestation/sound/misc/adminspawn.ogg
Labels: Administration

#25 Surgery Rework
  code/modules/clothing/gloves/color.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/advanced/bioware/vein_threading.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/dental_implant.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/hepatectomy.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/lobectomy.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/remove_embedded_object.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
Labels: Balance

#43 Preferences character preview bugfix, moth wing bugfixes
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/surgery/organs/wings.dm
Labels: bug

#41 Bad Food Disease
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Balance

#31 Shitcuritron
  beestation.dme
  code/game/sound.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  monkestation/code/modules/mob/living/simple_animal/bot/secbot.dm
  monkestation/icons/mob/aibots.dmi
  monkestation/sound/voice/pizzky/creep.ogg
  monkestation/sound/voice/pizzky/criminal.ogg
  monkestation/sound/voice/pizzky/freeze.ogg
  monkestation/sound/voice/pizzky/getowned.ogg
  monkestation/sound/voice/pizzky/god.ogg
  monkestation/sound/voice/pizzky/iamthelaw.ogg
  monkestation/sound/voice/pizzky/insult.ogg
  monkestation/sound/voice/pizzky/justice.ogg
  monkestation/sound/voice/pizzky/lmaoing.ogg
  monkestation/sound/voice/pizzky/mumble1.ogg
  monkestation/sound/voice/pizzky/mumble2.ogg
  monkestation/sound/voice/pizzky/mumble3.ogg
  monkestation/sound/voice/pizzky/mumble4.ogg
  monkestation/sound/voice/pizzky/radio.ogg
  monkestation/sound/voice/pizzky/secureday.ogg
  monkestation/sound/voice/pizzky/spawn1.ogg
  monkestation/sound/voice/pizzky/spawn2.ogg
Labels: Feature

#49 ERTs are now any race by default (except plasmamen)
  code/datums/ert.dm
  code/modules/admin/verbs/one_click_antag.dm
Labels: Administration

#51 Low-Pop Access Boost
  code/modules/jobs/job_types/_job.dm
Labels: enhancement

#48 Adds Flavor Text
  beestation.dme
  code/__DEFINES/say.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living_defines.dm
  monkestation/code/_HELPERS/html_emphasis.dm
Labels: Feature

#39 new bee icons
  beestation.dme
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  icons/mob/bees.dmi
  monkestation/code/modules/mob/living/simple_animal/hostile/bees.dm
Labels: enhancement, sprites

#50 Adds bald trait, makes wigs wearable in the neck slot
  beestation.dme
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  monkestation/code/datums/traits/neutral.dm
Labels: Feature

#57 Upstream test 1/18/22
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/exploration_corg.dmm
  _maps/shuttles/exploration_delta.dmm
  _maps/shuttles/exploration_fland.dmm
  _maps/shuttles/exploration_shuttle.dmm
  _maps/shuttles/science_outpost.dmm
  beestation.dme
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/processing/orbits.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/stunbaton.dm
  code/modules/cargo/orderconsole.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/exploration_crew/exploration_shuttle.dm
  code/modules/mining/laborcamp/laborshuttle.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/paperwork/folders.dm
  code/modules/photography/camera/silicon_camera.dm
  code/modules/projectiles/projectile/energy/net_snare.dm
  code/modules/ruins/spaceruin_code/caravanambush.dm
  code/modules/ruins/spaceruin_code/whiteshipruin_box.dm
  code/modules/shuttle/monastery.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/artifact_defenses.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/alien_artifact.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  code/modules/shuttle/white_ship.dm
  config/game_options.txt
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/mob/ai.dmi
  icons/mob/pets.dmi
  tools/requirements.txt
Labels: sprites, mapping, Config Update, tools

#27 Butt Organ & Emote Changes
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/keybinding.dm
  code/__DEFINES/robots.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/keybinding/_defines.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  monkestation/code/datums/components/crafting/recipes.dm
  monkestation/code/datums/keybinding/human.dm
  monkestation/code/datums/traits/good.dm
  monkestation/code/datums/traits/negative.dm
  monkestation/code/game/objects/effects/decals/cleanable/misc.dm
  monkestation/code/modules/mob/living/carbon/human/emote.dm
  monkestation/code/modules/mob/living/simple_animal/bot/buttbot.dm
  monkestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  monkestation/code/modules/surgery/organs/butts.dm
  monkestation/icons/mob/head.dmi
  monkestation/icons/obj/butts.dmi
  monkestation/icons/obj/misc/confetti.dmi
  monkestation/sound/effects/fart2.ogg
  monkestation/sound/effects/fart3.ogg
  monkestation/sound/effects/fart4.ogg
  monkestation/sound/effects/superfart.ogg
  monkestation/sound/misc/clap_short.ogg
  monkestation/sound/misc/dagothgod.ogg
Labels: Feature

#53 gloves of the north *SCREAM
  code/modules/clothing/gloves/miscellaneous.dm
Labels: enhancement

#52 Gives chemicals a default turf reaction which leaves a colored mess to clean up!
  beestation.dme
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  monkestation/code/game/objects/effects/decals/cleanable/chemicalmesses.dm
  monkestation/icons/obj/effects/splatter.dmi
  monkestation/icons/obj/effects/splatterbig.dmi
Labels: Feature

#59 Adds Captain the doggo
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  monkestation/code/modules/mob/living/simple_animal/friendly/dog.dm
  monkestation/icons/mob/pets.dmi
  monkestation/icons/mob/pets_held.dmi
Labels: mapping

#65 January 24th Upstream Updates
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/shuttles/pirate_default.dmm
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/brain_damage/severe.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/plushes.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/mob/inhands/plushes_lefthand.dmi
  icons/mob/inhands/plushes_righthand.dmi
  icons/mob/screen_retro.dmi
  icons/obj/device.dmi
  icons/obj/plushes.dmi
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/sanitize.js
  tgui/yarn.lock
Labels: sprites, mapping, TGUI-Changes
