Repository Monkestation/MonkeStation, pull requests merged in 2022-04, with the labels that each got.

#239 MonkeStation Monthly Update Rollup
  beestation.dme
  code/modules/admin/secrets.dm
  monkestation/code/_onclick/hud/fullscreen.dm
  monkestation/code/modules/admin/verbs/emergency_meeting.dm
  monkestation/icons/effects/emergency_meeting.dmi
  monkestation/sound/misc/sound_misc_emergency_meeting.ogg
Labels: Administration

#240 weregorilla
  beestation.dme
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  monkestation/code/modules/spells/spell_types/weregorilla.dm
Labels: Administration

#222 Ook the brig Prison Monke
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#249 Better Mixer Node Indicators
  icons/obj/atmospherics/components/trinary_devices.dmi
  tgui/packages/tgui/interfaces/AtmosMixer.js
Labels: sprites, TGUI-Changes

#207 E-N for Monke Code
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  monkestation/code/modules/mob/living/simple_animal/friendly/dog.dm
  monkestation/icons/mob/pets.dmi
Labels: mapping

#269 Wire Connections
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#271 Seed Vault Updates
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
Labels: mapping

#272 MetaStation incinerator toxins airlock fixes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#274 Messages can no longer be sent by servers to inactive PDAs
  code/game/machinery/telecomms/computers/message.dm
Labels: bug

#276 Exploration Shuttle Supplies
  _maps/shuttles/exploration_corg.dmm
  _maps/shuttles/exploration_delta.dmm
  _maps/shuttles/exploration_fland.dmm
  _maps/shuttles/exploration_kilo.dmm
  _maps/shuttles/exploration_shuttle.dmm
Labels: mapping

#211 Randomized_engines_port
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/game/machinery/suit_storage_unit.dm
  monkestation/_maps/RandomEngines/BoxStation/particle_accelerator.dmm
  monkestation/_maps/RandomEngines/BoxStation/supermatter.dmm
  monkestation/_maps/RandomEngines/MetaStation/particle_accelerator.dmm
  monkestation/_maps/RandomEngines/MetaStation/supermatter.dmm
  monkestation/code/game/objects/effects/spawners/lootdrop.dm
  monkestation/code/game/objects/effects/spawners/roomspawner.dm
  monkestation/code/modules/mapping/random_rooms.dm
Labels: mapping

#278 Condenses wigs into one object
  _maps/RandomRooms/10x5/sk_rdm011_barbershop.dmm
  _maps/RandomRooms/5x4/sk_rdm090_tinybarbershop.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_09_barbershop.dmm
  beestation.dme
  code/modules/clothing/head/misc_special.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  monkestation/code/modules/research/designs/biogenerator_designs.dm
Labels: mapping

#282 Autoname Cameras addition & Network tags for areas
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/camera.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: mapping

#283 Singularity Nullified Achievement & Singularity Interaction Refactor
  code/__DEFINES/achievements.dm
  code/datums/achievements/misc_achievements.dm
  code/modules/power/singularity/singularity.dm
  monkestation/code/modules/power/singularity/spatial_rift.dm
  monkestation/code/modules/projectiles/projectile/special/rocket.dm
  tools/HubMigrator/HubMigrator.dm
Labels: tools

#288 BoxStation Engineering Airlock Fix
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#295 [Mapper QoL] [Port] New icons for zones and items ported from /tg/
  beestation.dme
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/objects/effects/spawners/lootdrop.dm
  icons/effects/landmarks_spawners.dmi
  icons/effects/landmarks_static.dmi
  icons/turf/areas.dmi
Labels: sprites

#298 Ports Several Turf Decals From /tg/
  beestation.dme
  monkestation/code/game/objects/effects/decals/turfdecal.dm
  monkestation/code/game/objects/effects/decals/turfdecal/markings.dm
  monkestation/code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  monkestation/icons/turf/decals.dmi
Labels: mapping, Port

#300 Ghosts can see SM Stats [QoL] [PORT]
  code/game/objects/effects/countdown.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/supermatter/supermatter.dm
  tgui/packages/tgui/interfaces/NtosSupermatterMonitor.js
  tgui/packages/tgui/interfaces/SupermatterMonitor.js
Labels: TGUI-Changes, Quality of Life, Port

#293 id_tag and network_id Standardized
  code/game/machinery/airlock_control.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/embedded_controller/airlock_controller.dm
  code/game/objects/objs.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/meter.dm
Labels: Refactor, Port

#291 Flatulynt Chemical Uses
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/hydroponics/grown/beans.dm
Labels: enhancement

#290 Baja Blast Fixes
  monkestation/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  monkestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
  monkestation/code/modules/reagents/reagent_containers/medspray.dm
  monkestation/code/modules/reagents/reagent_containers/spray.dm
Labels: bug, Refactor

#289 Craftable Ook Mask
  monkestation/code/datums/components/crafting/recipes.dm
Labels: enhancement

#304 Adds some new plushies
  beestation.dme
  code/game/objects/items/plushes.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  monkestation/_maps/RandomRooms/10x5/mailroom_10x5.dmm
  monkestation/code/game/objects/items/plushes.dm
  monkestation/icons/obj/plushes.dmi
Labels: Feature
