Repository Monkestation/MonkeStation, pull requests merged in 2022-03, with the labels that each got.

#161 make dizziness use screen_shake, add additional override
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/mob_helpers.dm
Labels: enhancement, testmerged, NEEDS TESTMERGE

#165 emergency firesuit can now hold oxygen tanks
  code/modules/clothing/suits/utility.dm
Labels: enhancement

#193 Removal of Unused Golems
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/ruins/lavaland_ruin_code.dm
  sound/misc/Cyka Blyat.ogg
  sound/misc/Russian_Anthem_chorus.ogg
  sound/misc/capitialism.ogg
  sound/misc/mymoney.ogg
Labels: sound

#171 WH's NEW MORE RANDOM ROOMS
  beestation.dme
  code/modules/mapping/random_rooms.dm
  monkestation/_maps/RandomRooms/10x10/SECONDARYAIWORSHIPROOM10x10.dmm
  monkestation/_maps/RandomRooms/10x5/DRUGDEALERHOBOS.dmm
  monkestation/_maps/RandomRooms/10x5/skwh_rdm157_slimestorage.dmm
  monkestation/_maps/RandomRooms/3x3/secretivemaintwatercollectorroom.dmm
  monkestation/_maps/RandomRooms/3x5/maskroom3x5.dmm
  monkestation/_maps/RandomRooms/5x3/randomlostartifact.dmm
  monkestation/_maps/RandomRooms/blankroom10x10.dmm
  monkestation/_maps/RandomRooms/blankroom10x5.dmm
  monkestation/_maps/RandomRooms/blankroom3x5.dmm
  monkestation/_maps/RandomRooms/blankroom5x3.dmm
  monkestation/_maps/RandomRooms/blankroom5x4.dmm
  monkestation/_maps/random_rooms.dm
Labels: enhancement

#199 Removes Annoying Ambimalf AI ambience
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/ruins/space.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  sound/ambience/ambimalf.ogg
Labels: sound

#213 Upstream 03_18_22
  .github/PULL_REQUEST_TEMPLATE.md
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/machines.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/game.dm
  code/_globalvars/lists/poll_ignore.dm
  code/_onclick/ai.dm
  code/controllers/globals.dm
  code/controllers/subsystem/acid.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/fire_burning.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/mapping.dm
  code/datums/components/crafting/tailoring.dm
  code/datums/components/larryknife.dm
  code/datums/datum.dm
  code/datums/diseases/transformation.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
  code/datums/position_point_vector.dm
  code/datums/weakrefs.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/objects/items.dm
  code/game/objects/items/dna_injector.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/client/client_procs.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/wizard/rpgloot.dm
  code/modules/library/lib_machines.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/power/lighting.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/recycling/disposal/construction.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/surgery/organs/wings.dm
  code/modules/vending/security.dm
  icons/mob/inhands/misc/larry.dmi
  icons/obj/lighting_overlay.dmi
  tgui/packages/tgui/interfaces/CloningConsole.js
  tools/requirements.txt
Labels: sprites, mapping, tools, TGUI-Changes, GitHub

#203 Adds an Additional Lifeform Stasis Unit to Meta's Medical
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#212 Weeb Trait Changes
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organs/tails.dm
  monkestation/code/game/objects/items/anime.dm
Labels: testmerged

#152 Reverts to original E keybind, updates other desc
  code/__DEFINES/obj_flags.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/misc_special.dm
  monkestation/code/datums/keybinding/human.dm
  monkestation/code/modules/clothing/shoes/magboots.dm
  monkestation/code/modules/mob/living/inventory.dm
Labels: testmerged

#225 Upstream 03_26_22
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/chat.dm
  code/__DEFINES/flags.dm
  code/__HELPERS/sanitize_values.dm
  code/_compile_options.dm
  code/controllers/subsystem/explosion.dm
  code/controllers/subsystem/tgui.dm
  code/datums/diseases/advance/advance.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/objects/items/cards_ids.dm
  code/game/world.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/disease/disease_disease.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/client/preferences_savefile.dm
  code/modules/events/spacevine.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/mentor/mentorsay.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  code/modules/power/smes.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/artifact_defenses.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/research_disks.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/alien_artifact.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/surgery.dm
  icons/obj/card.dmi
  icons/obj/computer.dmi
  icons/obj/structures.dmi
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: sprites, mapping, TGUI-Changes

#231 Junk Food Reduction
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/cargo/packs.dm
  code/modules/exploration_crew/exploration_vendor.dm
  code/modules/mining/machine_vending.dm
  code/modules/vending/security.dm
  code/modules/vending/snack.dm
Labels: mapping
