Repository Monkestation/MonkeStation, pull requests merged in 2022-05, with the labels that each got.

#324 Reorganizes robot defines
  code/__DEFINES/misc.dm
  code/__DEFINES/robots.dm
  code/datums/ai_laws.dm
  code/datums/wires/robot.dm
  code/game/machinery/transformer.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Administration

#297 TGUI Airlock Controller [PORT]
  code/game/machinery/embedded_controller/airlock_controller.dm
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  code/game/objects/objs.dm
  tgui/packages/tgui/interfaces/AirlockController.js
Labels: TGUI-Changes, Refactor, Port

#299 Add Plating to Metal Foams [QoL] [PORT]
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/walls.dm
  monkestation/icons/turf/walls/foam_base_wall.dmi
Labels: enhancement, Quality of Life, Port

#308 Ling Spawned Teratoma can no longer use guns
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Balance

#309 Airlock Mapping Helpers [PORT]
  beestation.dme
  code/__DEFINES/access.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/doors/airlock.dm
  code/modules/mapping/access_helpers.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: sprites

#310 Mushroom Replication Removal
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_standruin.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/shuttles/whiteship_fland.dmm
  code/game/objects/effects/glowshroom.dm
Labels: mapping

#317 Pandora Nerf
  _maps/RuinGeneration/13x17_pizzaroom.dmm
  beestation.dme
  monkestation/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora_exploration.dm
Labels: mapping, Balance

#311 reduce wheelchair grief
  code/modules/vehicles/wheelchair.dm
Labels: enhancement, Balance

#325 Pubby Random Bar
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#327 WALTER FOR LAWYER OFFICE PET
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#334 Headset Radio TGUI fix
  tgui/packages/tgui/interfaces/Radio.js
Labels: TGUI-Changes

#343 New MetaStation Telecoms Hallway
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#357 Generalizes SM Area Names and adds new area icons for random engine/bar areas
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__HELPERS/areas.dm
  code/game/area/Space_Station_13_areas.dm
  code/modules/admin/verbs/debug.dm
  code/modules/antagonists/swarmer/swarmer.dm
  icons/turf/areas.dmi
  monkestation/_maps/RandomEngines/BoxStation/supermatter.dmm
  monkestation/_maps/RandomEngines/MetaStation/supermatter.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/clown_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/default_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/syndi_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/vietmoth_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Meta/default_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Meta/grungy_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Meta/med_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Meta/tribal_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/default_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/hobo_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/japanese_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Pubby/pool_bar.dmm
Labels: sprites, mapping, Administration

#374 Greg
  icons/emoji.dmi
Labels: sprites

#323 [TM Ready] Monkey can have a little Donut - Return of Donutstation
  README.md
  _maps/donutstation.json
  _maps/map_files/DonutStation/DonutStation.dmm
  _maps/shuttles/emergency_donut.dmm
  code/datums/shuttles.dm
  config/maps.txt
Labels: mapping, Config Update, testmerged

#373 Debtor Rework
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/3x3/sk_rdm092_hobohut.dmm
  beestation.dme
  code/datums/brain_damage/phobia.dm
  code/modules/jobs/job_types/gimmick.dm
  monkestation/_maps/RandomRooms/10x10/SECONDARYAIWORSHIPROOM10x10.dmm
  monkestation/_maps/RandomRooms/10x5/DRUGDEALERHOBOS.dmm
  monkestation/code/game/objects/items/granters.dm
  monkestation/code/modules/uplink/uplink_items.dm
Labels: mapping

#379 Fixes Syndie Assassination Target + Cybersun Hardsuit
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: sprites

#366 Dynamic Improvements
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: testmerged

#347 [TM FIRST] HoleStation - The Dedicated Deadpop Map
  _maps/holestation.json
  _maps/map_files/HoleStation/holestation.dmm
  beestation.dme
  config/maps.txt
  monkestation/_maps/shuttles/cargo_holestation.dmm
  monkestation/_maps/shuttles/emergency_holestation.dmm
  monkestation/_maps/shuttles/exploration_holestation.dmm
  monkestation/_maps/shuttles/mining_holestation.dmm
  monkestation/code/datums/shuttles.dm
Labels: mapping, Config Update

#392 Holestation Patch One
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping

#386 Adds some new emotes and an IPC dialup sound on revival [PORT]
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/emote.dm
  sound/voice/dialup.ogg
Labels: sound

#398 Holestation Patch 2: Revengeance
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping

#406 Mixer_0 icon off by one pixel
  icons/obj/atmospherics/components/trinary_devices.dmi
Labels: sprites

#394 Coding Guides and readme.md Clean Up
  .github/guides/DOWNLOADING.md
  .github/guides/HARDDELETES.md
  .github/guides/MC_tab.md
  .github/guides/RUNNING_A_SERVER.md
  .github/guides/STANDARDS.md
  .github/guides/STYLE.md
  README.md
Labels: GitHub

#400 APC Code Clean and New Sounds
  beestation.dme
  code/__DEFINES/mapping/directional.dm
  code/__DEFINES/power/apc_defines.dm
  code/__DEFINES/power/power.dm
  code/_globalvars/misc.dm
  code/game/area/areas.dm
  code/game/objects/items/apc_frame.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/power/apc.dm
  code/modules/power/apc/apc_appearance.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_malf.dm
  code/modules/power/apc/apc_mapping.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/apc/apc_tool_act.dm
  code/modules/power/lighting.dm
  code/modules/power/monitor.dm
  code/modules/power/power.dm
  monkestation/sound/machines/apc/PowerDown_001.ogg
  monkestation/sound/machines/apc/PowerSwitch_Cover.ogg
  monkestation/sound/machines/apc/PowerSwitch_Off.ogg
  monkestation/sound/machines/apc/PowerSwitch_Place.ogg
  monkestation/sound/machines/apc/PowerUp_001.ogg
Labels: testmerged

#396 PTSD: Now standard issue for all heads of staff [PORT]
  code/game/objects/items/melee/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  icons/obj/guns/energy.dmi
Labels: sprites, testmerged

#416 Holestation Medical Redo
  _maps/map_files/HoleStation/holestation.dmm
Labels: mapping
