Repository Monkestation/MonkeStation, pull requests merged in 2022-09, with the labels that each got.

#685 Particool - Port of a port
  beestation.dme
  code/__DEFINES/vv.dm
  code/game/atoms_movable.dm
  code/modules/admin/holder2.dm
  code/modules/client/client_procs.dm
  code/modules/hydroponics/grown/towercap.dm
  icons/effects/particles/weather.dmi
  monkestation/code/modules/particles/byond_particles/emitter/fire.dm
  monkestation/code/modules/particles/byond_particles/emitter/smoke.dm
  monkestation/code/modules/particles/byond_particles/emitter/weather.dm
  monkestation/code/modules/particles/byond_particles/particle/fire.dm
  monkestation/code/modules/particles/byond_particles/particle/rain.dm
  monkestation/code/modules/particles/byond_particles/particle/smoke.dm
  monkestation/code/modules/particles/byond_particles/particle_holder.dm
  monkestation/code/modules/particles/byond_particles/particle_procs.dm
  monkestation/code/modules/particles/byond_particles/particle_usage.md
  monkestation/code/modules/particles/byond_particles/particool.dm
  tgui/.eslintrc.yml
  tgui/packages/tgui/interfaces/Particool.js
Labels: sprites, Administration, TGUI-Changes, testmerged

#648 Mimics
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  html/antagtips/mimic.html
  html/img/mimic.png
  icons/misc/language.dmi
  monkestation/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  monkestation/code/modules/antagonists/mimic/mimic.dm
  monkestation/code/modules/antagonists/mimic/mimic_antag.dm
  monkestation/code/modules/language/language_holder.dm
  monkestation/code/modules/language/mimic.dm
  monkestation/icons/mob/animal.dmi
  monkestation/sound/ambience/antag/mimic.ogg
  monkestation/sound/creatures/mimic/mimicabsorb.ogg
  monkestation/sound/creatures/mimic/mimicattack.ogg
  monkestation/sound/creatures/mimic/mimicsplit.ogg
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: sprites, TGUI-Changes

#698 Particool 2: Particooler
  beestation.dme
  code/__DEFINES/particles.dm
  code/__DEFINES/vv.dm
  code/game/atoms_movable.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/hydroponics/grown/towercap.dm
  icons/effects/particles/rocks.dmi
  icons/effects/particles/shapes.dmi
  icons/obj/lighting.dmi
  monkestation/code/modules/particles/byond_particles/emitter/burst.dm
  monkestation/code/modules/particles/byond_particles/emitter/fire.dm
  monkestation/code/modules/particles/byond_particles/emitter/misc.dm
  monkestation/code/modules/particles/byond_particles/emitter/smoke.dm
  monkestation/code/modules/particles/byond_particles/emitter/spark.dm
  monkestation/code/modules/particles/byond_particles/particle/burst.dm
  monkestation/code/modules/particles/byond_particles/particle/fire.dm
  monkestation/code/modules/particles/byond_particles/particle/misc.dm
  monkestation/code/modules/particles/byond_particles/particle/smoke.dm
  monkestation/code/modules/particles/byond_particles/particle/spark.dm
  monkestation/code/modules/particles/byond_particles/particle_holder.dm
  monkestation/code/modules/particles/byond_particles/particle_procs.dm
Labels: sprites

#649 Updates Thin Firedoors Icons
  icons/obj/doors/edge_Doorfire.dmi
Labels: sprites

#686 Fixes processing of deleted objects in SSair
  code/controllers/subsystem/air.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/airlock_cycle_control.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/spaceheater.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/power/generator.dm
  code/modules/power/supermatter/supermatter.dm
  monkestation/code/modules/power/rbmk/rbmk.dm
Labels: testmerged

#701 Fixes the missing turf_decal tile icons
  icons/turf/decals.dmi
  monkestation/icons/turf/decals.dmi
Labels: sprites

#621 Mentor QOL: Imaginary Friend Edition
  beestation.dme
  code/datums/brain_damage/imaginary_friend.dm
  code/modules/client/client_procs.dm
  code/modules/mentor/mentorhelp.dm
  monkestation/code/modules/clothing/outfits/special.dm
  monkestation/code/modules/mentor/mentorfriend.dm
Labels: testmerged

#720 Imaginary Friend verb fix
  code/modules/admin/admin_verbs.dm
  code/modules/mentor/mentor_verbs.dm
  monkestation/code/modules/mentor/mentorfriend.dm
Labels: Administration

#722 Small Pirate ship expansion
  _maps/shuttles/pirate_default.dmm
Labels: mapping

#729 Fixes pathfinding not checking diagonal passability properly.
  code/__HELPERS/path.dm
  code/game/machinery/doors/firedoor.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: testmerged

#713 Adds two new illegal shuttles
  _maps/shuttles/emergency_metabananium.dmm
  _maps/shuttles/emergency_pods.dmm
  monkestation/code/datums/shuttles.dm
Labels: mapping

#609 The great gas expansion
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/reactions.dm
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/grenades/atmos_grenade.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/open/_open.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/gas_recipe_machines/atmos_machine_recipes.dm
  code/modules/atmospherics/machinery/components/gas_recipe_machines/crystallizer.dm
  code/modules/atmospherics/machinery/components/gas_recipe_machines/crystallizer_items.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/power/cell.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/lungs.dm
  icons/effects/atmospherics.dmi
  icons/effects/ore_visuals.dmi
  icons/mob/inhands/weapons/axes_lefthand.dmi
  icons/obj/atmos.dmi
  icons/obj/atmospherics/components/machines.dmi
  icons/obj/grenade.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/power.dmi
  icons/obj/stack_objects.dmi
  icons/obj/statue.dmi
  monkestation/code/datums/components/crafting/recipes.dm
  monkestation/code/datums/components/hot_ice.dm
  monkestation/code/datums/materials/basemats.dm
  monkestation/code/game/machinery/electrolyzer.dm
  monkestation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  monkestation/code/game/objects/items/stacks/ammonia_crystals.dm
  monkestation/code/game/objects/items/stacks/hot_ice.dm
  monkestation/code/game/objects/items/stacks/sheets/mineral.dm
  monkestation/code/modules/research/designs/machine_designs.dm
  monkestation/icons/obj/telescience.dmi
  tgui/packages/tgui/interfaces/Crystallizer.js
  tgui/packages/tgui/interfaces/Electrolyzer.js
Labels: sprites, TGUI-Changes

#732 Flash/Deafen Updates
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/grenades/flashbang.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/surgery/organs/ears.dm
  icons/mob/screen_alert.dmi
  sound/weapons/flash_ring.ogg
  sound/weapons/flashbang.ogg
Labels: sprites, sound, testmerged

#631 OPERATION CATBOX
  _maps/RandomRooms/5x4/sk_rdm035_deltasurgery.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  monkestation/_maps/RandomEngines/BoxStation/particle_accelerator.dmm
  monkestation/_maps/RandomEngines/BoxStation/supermatter.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/default_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/syndi_bar.dmm
  monkestation/_maps/RandomRooms/_Bars/Box/vietmoth_bar.dmm
Labels: mapping, testmerged

#740 Rearranges Medbay storage and adds another surgery door
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#724 Replaces the gross language in the beepsky insult
  code/game/sound.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  sound/voice/beepsky/insult.ogg
  sound/voice/complionator/emag.ogg
Labels: sound

#744 Minor Medical Modifications.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/HoleStation/holestation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#748 BoxStationBandaid
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#676 Vending Machine Tabs
  code/game/objects/items/vending_items.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/vending/_vending.dm
  code/modules/vending/clothesmate.dm
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-regular-400.ttf
  html/font-awesome/webfonts/fa-regular-400.woff
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.ttf
  html/font-awesome/webfonts/fa-solid-900.woff
  html/font-awesome/webfonts/fa-v4compatibility.ttf
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: TGUI-Changes, testmerged

#689 Simian Uniform Update
  code/datums/greyscale/json_configs/catgloves.json
  code/datums/greyscale/json_configs/catgloves_worn.json
  code/datums/greyscale/json_configs/kimono_fancy.json
  code/datums/greyscale/json_configs/kimono_fancy_worn.json
  code/modules/mob/living/carbon/human/update_icons.dm
  monkestation/code/datums/greyscale/greyscale_configs.dm
  monkestation/code/modules/clothing/gloves/color.dm
  monkestation/code/modules/clothing/under/jobs/engineering.dm
  monkestation/icons/mob/catgloves.dmi
  monkestation/icons/mob/engiskirts.dmi
  monkestation/icons/mob/gloves.dmi
  monkestation/icons/mob/kimono.dmi
  monkestation/icons/mob/species/simian/simian_gloves.dmi
  monkestation/icons/mob/species/simian/simian_shoes.dmi
  monkestation/icons/mob/species/simian/simian_suits.dmi
  monkestation/icons/mob/species/simian/simian_uniforms.dmi
  monkestation/icons/mob/suit.dmi
  monkestation/icons/mob/uniform.dmi
  monkestation/icons/obj/clothing/catgloves.dmi
  monkestation/icons/obj/clothing/engiskirts.dmi
  monkestation/icons/obj/clothing/gloves.dmi
  monkestation/icons/obj/clothing/kimono.dmi
  monkestation/icons/obj/clothing/suits.dmi
  monkestation/icons/obj/clothing/uniforms.dmi
Labels: testmerged

#756 Box moment
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping
