Repository Monkestation/MonkeStation, pull requests merged in 2023-01, with the labels that each got.

#877 attempt to fix box runtiming
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#864 Fixes metastation's atmospheric flaps windoor
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#887 makes some of the shotgun sprites look as if they were held with 2 hands
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/64x_guns_right.dmi
Labels: sprites

#909 Changes CACHE_ASSETS val to 0 in config.txt
  config/config.txt
Labels: Config Update

#856 Ports Biddle Verbs and Speech Controller from TG
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/callbacks.dm
  code/__DEFINES/input.dm
  code/__DEFINES/speech_controller.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/time.dm
  code/__DEFINES/verb_manager.dm
  code/__HELPERS/turfs.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/speech_controller.dm
  code/controllers/subsystem/verb_manager.dm
  code/datums/verb_callbacks.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  code/modules/tgui/tgui.dm
Labels: Port, NEEDS TESTMERGE

#833 Lights start off if no one is present, lights now have a delayed turn on.
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__HELPERS/areas.dm
  code/__HELPERS/type_processing.dm
  code/controllers/subsystem/ticker.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/machinery/lightswitch.dm
  code/modules/power/lighting/light.dm
  sound/effects/lights/light_on.ogg
Labels: mapping, sound, Feature
